Running on host node005
Time is Seg Abr 22 22:09:51 -03 2019
Directory is /home/david/git-repos/ann_training
Slurm job ID is 5398
This job runs on the following machines:
node005
Running /home/david/vp368cpu/bin/python /home/david/git-repos/ann_training/main_ann_35.py
Using TensorFlow backend.
WARNING:tensorflow:From /home/david/vp368cpu/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py:423: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
22/04/2019 22:10:28 - From /home/david/vp368cpu/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py:423: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/david/vp368cpu/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
22/04/2019 22:10:29 - From /home/david/vp368cpu/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-04-22 22:10:29.330192: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200205000 Hz
2019-04-22 22:10:29.331183: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x52c0a960 executing computations on platform Host. Devices:
2019-04-22 22:10:29.331223: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
TF version 1.13.1
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
gaussian_noise_1 (GaussianNo (None, 16)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 48)                816       
_________________________________________________________________
dense_2 (Dense)              (None, 10)                490       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 11        
=================================================================
Total params: 1,317
Trainable params: 1,317
Non-trainable params: 0
_________________________________________________________________

....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................dict_keys(['val_loss', 'val_mean_absolute_error', 'val_mean_squared_error', 'loss', 'mean_absolute_error', 'mean_squared_error'])
Traceback (most recent call last):
  File "/home/david/git-repos/ann_training/main_ann_35.py", line 268, in <module>
    main()
  File "/home/david/git-repos/ann_training/main_ann_35.py", line 108, in main
    Retrieval.autoExecReg()
  File "/home/david/git-repos/ann_training/src/training_ann_35.py", line 334, in autoExecReg
    self.plot_history(history)
  File "/home/david/git-repos/ann_training/src/training_ann_35.py", line 471, in plot_history
    plt.ylim([0, ylim_max])
  File "/home/david/vp368cpu/lib/python3.6/site-packages/matplotlib/pyplot.py", line 1479, in ylim
    ret = ax.set_ylim(*args, **kwargs)
  File "/home/david/vp368cpu/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 3617, in set_ylim
    top = self._validate_converted_limits(top, self.convert_yunits)
  File "/home/david/vp368cpu/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 3139, in _validate_converted_limits
    raise ValueError("Axis limits cannot be NaN or Inf")
ValueError: Axis limits cannot be NaN or Inf

real	52m53.438s
user	113m17.712s
sys	20m48.073s
